---
collections:
  - name: community.zabbix
    version: 3.3.0
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 10.7.0
  - name: newrelic.newrelic_agents
    version: 1.0.4
