---
collections:
  - name: community.zabbix
    version: 2.0.0
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=8.0.0"
  - name: newrelic.newrelic_agents
    version: 1.0.4
  - name: community.docker
    version: ">=3.4.0"
roles:
  - src: artis3n.tailscale
  - src: staticdev.pyenv
  - src: geerlingguy.docker
  - src: stephdewit.nvm
  - src: avanov.pyenv
  - src: patrickjahns.promtail
