# ---
# all:
#   hosts:
#     vagrant:
#       ansible_host: 127.0.0.1
#       ansible_port: 2222
#       ansible_user: vagrant
#       # If using password authentication
#       # ansible_ssh_pass: YOUR_ROOT_PASSWORD
#       # If using key authentication
#       ansible_ssh_private_key_file: /Users/timothybryant/DEV/homelab/automation_ansible/.vagrant/machines/default/vmware_desktop/private_key

---
all:
  children:
    vagrant:
      hosts:
        vagrant:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: vagrant
          ansible_ssh_private_key_file: /Users/timothybryant/DEV/homelab/automation_ansible/.vagrant/machines/default/vmware_desktop/private_key
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa"
