---
- name: Proxmox node | Disable APT translation downloads
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/99-disable-translations
    content: 'Acquire::Languages "none";'
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Proxmox node | Force APT to use IPv4
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/99force-ipv4
    content: 'Acquire::ForceIPv4 "true";'
    owner: root
    group: root
    mode: "0644"
  become: true
