[master]
k3s-0 ansible_host=192.168.86.180 ansible_connection=ssh ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_master_key
k3s-1 ansible_host=192.168.86.185 ansible_connection=ssh ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_master_key
k3s-2 ansible_host=192.168.86.186 ansible_connection=ssh ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_master_key

[node]
k3s-0-worker ansible_host=192.168.86.190 ansible_connection=ssh ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_master_key
k3s-1-worker ansible_host=192.168.86.191 ansible_connection=ssh ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_master_key
k3s-2-worker ansible_host=192.168.86.192 ansible_connection=ssh ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_master_key

[k3s_cluster:children]
master
node
