- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: Reload systemd

- name: Restart k3s
  ansible.builtin.systemd:
    name: "{{ k3s_service_name }}"
    state: restarted
  listen: Restart k3s
